# Generated by Django 4.0.4 on 2022-04-18 06:46

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[('C', 'Cash payment')], default='C', verbose_name=payment.models.PaymentType)),
                ('status', models.IntegerField(choices=[(10, 'Initiated'), (20, 'Pending'), (30, 'Paid'), (-10, 'Cancelled')], default=10, verbose_name=payment.models.PaymentStatus)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
