# Generated by Django 4.0.4 on 2022-04-18 09:16

from decimal import Decimal
from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('C', 'Cash payment')], default='C', max_length=2, verbose_name=payment.models.PaymentType),
        ),
    ]
