# Generated by Django 4.0.4 on 2022-05-05 15:52

from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0007_alter_profile_gender'),
        ('education', '0003_alter_educationlevel_is_higher_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(10, 'Pending Tutor Selection'), (20, 'Ongoing'), (30, 'Complete')], default=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education_level', models.ForeignKey(on_delete=education.models.EducationLevel, to='education.educationlevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studied_private_classes', to='profile.profile')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.subject')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_private_classes', to='profile.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateClassOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('private_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='private.privateclass')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
