# Generated by Django 4.0.4 on 2022-05-06 16:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_profile_gender'),
        ('education', '0003_alter_educationlevel_is_higher_education'),
        ('private', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateclass',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.educationlevel'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='privateclassoffer',
            unique_together={('tutor', 'private_class')},
        ),
    ]
