# Generated by Django 4.0.4 on 2022-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_alter_privateclass_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclassoffer',
            name='status',
            field=models.IntegerField(choices=[(10, 'Pending'), (20, 'Cancelled'), (30, 'Accepted')], default=10),
        ),
    ]
