# Generated by Django 4.0.4 on 2022-05-08 06:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_profile_gender'),
        ('education', '0003_alter_educationlevel_is_higher_education'),
        ('private', '0003_privateclassoffer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateclass',
            name='rate',
        ),
        migrations.AddField(
            model_name='privateclass',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='no_of_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Registration'), ('T', 'Pending Tutor Selection'), ('S', 'Class has started'), ('E', 'Class Has Ended'), ('C', 'Cancelled')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='education.subject'),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_classes_tutored', to='profile.profile'),
        ),
    ]
