# Generated by Django 4.0.4 on 2022-07-16 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0004_remove_privateclass_rate_privateclass_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
