# Generated by Django 4.0.4 on 2022-04-16 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import profile.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0002_subject_description'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutor',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.educationlevel'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='gender',
            field=enumfields.fields.EnumField(enum=profile.enums.Gender, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=enumfields.fields.EnumField(enum=profile.enums.Gender, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
