# Generated by Django 4.0.4 on 2022-04-17 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0002_student_user_tutor_age_tutor_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Tutor')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Tutor')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
