# Generated by Django 4.0.4 on 2022-04-18 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import profile.enums


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_educationlevel_is_higher_education'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0003_student_user_type_tutor_user_type_alter_student_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('user_type', models.CharField(choices=[('S', 'Student'), ('T', 'Tutor')], default='S', max_length=1)),
                ('age', models.IntegerField(null=True)),
                ('gender', enumfields.fields.EnumField(enum=profile.enums.Gender, max_length=10, null=True)),
                ('description', models.TextField(null=True)),
                ('education_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.educationlevel')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
