# Generated by Django 4.0.4 on 2022-04-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_profile_remove_tutor_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
