# Generated by Django 4.0.4 on 2022-05-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
