# Generated by Django 4.0.4 on 2023-01-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
