# Generated by Django 4.0.4 on 2022-04-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_class_students_alter_class_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
