# Generated by Django 4.0.4 on 2022-04-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_remove_profile_name'),
        ('booking', '0004_class_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes_joined', to='profile.profile'),
        ),
    ]
