# Generated by Django 4.0.4 on 2022-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student_capacity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
