# Generated by Django 4.0.4 on 2022-04-29 04:08

import booking.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_class_student_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(10, 'Pending'), (20, 'Confirmed'), (-10, 'Cancelled')], default=10, verbose_name=booking.models.BookingStatus),
        ),
        migrations.AlterField(
            model_name='class',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='class',
            name='no_of_times',
            field=models.IntegerField(default=0),
        ),
    ]
