# Generated by Django 4.0.4 on 2022-04-29 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_amount_alter_payment_type'),
        ('booking', '0007_booking_status_alter_class_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payment.payment'),
        ),
    ]
