# Generated by Django 4.0.4 on 2022-05-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Registration'), ('S', 'Class has started'), ('E', 'Class Has Ended'), ('C', 'Cancelled')], default='P', max_length=2),
        ),
    ]
