# Generated by Django 4.0.4 on 2022-05-08 06:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_profile_gender'),
        ('education', '0003_alter_educationlevel_is_higher_education'),
        ('booking', '0009_class_start_date_class_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('duration', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, null=True)),
                ('no_of_times', models.IntegerField(default=0)),
                ('rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('P', 'Pending Registration'), ('T', 'Pending Tutor Selection'), ('S', 'Class has started'), ('E', 'Class Has Ended'), ('C', 'Cancelled')], default='P', max_length=2)),
                ('is_remote', models.BooleanField(default=False)),
                ('student_capacity', models.PositiveSmallIntegerField(null=True)),
                ('education_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.educationlevel')),
                ('students', models.ManyToManyField(related_name='classes_enrolled', to='profile.profile')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='education.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes_tutored', to='profile.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.academyclass'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
