# Generated by Django 4.0.4 on 2022-07-16 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_academyclass_alter_booking_booking_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyclass',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
