# Generated by Django 4.0.4 on 2023-01-21 19:40

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_academyclass_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(10, 'Pending Tutor'), (20, 'Pending Payment'), (30, 'Confirmed'), (-10, 'Cancelled')], default=10, verbose_name=booking.models.BookingStatus),
        ),
    ]
