# Generated by Django 4.0.4 on 2022-04-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationlevel',
            name='is_higher_education',
            field=models.BooleanField(default=False),
        ),
    ]
